version = 1

[update]
always = true
require_automerge_label = false

[merge.automerge_dependencies]
usernames = ["dependabot"]
versions = ["minor", "patch"]

[update]
ignored_usernames = ["dependabot"]
